<?php

/**
 * @file
 * Primary module hooks for Moody Overrides module.
 */

/**
 * Implements hook_preprocess_responsive_image_formatter().
 */
function moody_overrides_preprocess_responsive_image_formatter(&$variables) {
  // Get the current active route.
  $route = \Drupal::routeMatch()->getRouteName();
  
  // Check if we're in a node view context.
  if (strpos($route, 'entity.node.canonical') === 0) {
    // Check if the responsive image style is one we want to override.
    if (isset($variables['responsive_image_style_id'])) {
      $current_style = $variables['responsive_image_style_id'];
      if ($current_style === 'utexas_responsive_image_pu_portrait') {
        // Override with our custom style
        $variables['responsive_image_style_id'] = 'moody_promo_unit_portrait';
        $variables["responsive_image"]["#responsive_image_style_id"] = 'moody_promo_unit_portrait';
      }
      if ($current_style === "utexas_responsive_image_pu_landscape") {
        // Override with our custom style
        $variables['responsive_image_style_id'] = 'moody_promo_unit_landscape';
        $variables["responsive_image"]["#responsive_image_style_id"] = 'moody_promo_unit_landscape';
      }
    }
  }
}
