<?php

use Drupal\moody_layout_restrictions\Restrictions;

/**
 * Implements hook_plugin_filter_block__layout_builder_alter().
 */
function moody_layout_restrictions_plugin_filter_block__layout_builder_alter(array &$definitions, array $extra): void {
  $definitions = Restrictions::blocks($definitions, Restrictions::settings($extra));
}

/**
 * Implements hook_plugin_filter_layout__layout_builder_alter().
 */
function moody_layout_restrictions_plugin_filter_layout__layout_builder_alter(array &$definitions, array $extra): void {
  $allowed = Restrictions::settings($extra)['entity_view_mode_restriction']['allowed_layouts'] ?? [];
  if ($allowed) {
    $definitions = array_intersect_key($definitions, array_flip($allowed));
  }
}
