<?php

/**
 * @file
 * Contains moody_quotation.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function moody_quotation_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the moody_quotation module.
    case 'help.page.moody_quotation':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A styled quotation') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function moody_quotation_theme() {
  return [
    'moody_quotation' => [
      'variables' => [
        'quote' => NULL,
        'style' => NULL,
        'author' => NULL,
        'media' => NULL,
      ],
      'template' => 'moody-quotation',
    ],
  ];
}
