block.settings.moody_feature_page_feature_pages_editors_picks:
  type: block_settings
  label: 'Feature Pages - Editors Picks block'
  mapping:
    selected_nodes:
      type: sequence
      label: 'Selected nodes'
      sequence:
        type: string
        label: 'Node ID'
    items:
      type: sequence
      label: "Ordered Editor's Picks items"
      sequence:
        type: mapping
        mapping:
          type:
            type: string
            label: 'Item type'
          node:
            type: string
            label: 'Feature Page node ID'
          image:
            type: string
            label: 'Custom image media ID'
          subhead_1:
            type: string
            label: 'Custom first subhead'
          subhead_2:
            type: string
            label: 'Custom second subhead'
          title:
            type: string
            label: 'Custom title'
          body:
            type: text
            label: 'Custom body'
          url:
            type: string
            label: 'Custom link URL'
    image_style:
      type: string
      label: 'Image style override'

block.settings.moody_feature_page_media_mentions:
  type: block_settings
  label: 'Moody Media Mentions block'
  mapping:
    items:
      type: sequence
      label: 'Media mentions'
      sequence:
        type: mapping
        mapping:
          media_source:
            type: string
            label: 'Media source name'
          headline:
            type: string
            label: 'Headline'
          link:
            type: string
            label: 'Link'
          date:
            type: string
            label: 'Date'

block.settings.moody_feature_page_news_and_announcements:
  type: block_settings
  label: 'News and Announcements block'
  mapping:
    items:
      type: sequence
      label: 'News and announcement items'
      sequence:
        type: mapping
        mapping:
          category:
            type: string
            label: 'Category'
          date:
            type: string
            label: 'Date'
          date_format:
            type: string
            label: 'Date display format'
          body:
            type: text_format
            label: 'Body'
          link:
            type: string
            label: 'Link'
          link_text:
            type: string
            label: 'Link text'
