<?php

/**
 * @file
 * Contains moody_subsite.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function moody_subsite_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the moody_subsite module.
    case 'help.page.moody_subsite':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provide custom entity for Moody Subsite functionality') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function moody_subsite_theme() {
  return [
    'moody_subsite' => [
      'render element' => 'children',
    ],
    'moody_subsite_menu' => [
      'variables' => [
        'title' => NULL,
        'link' => NULL,
      ],
      'template' => 'moody-subsite-menu',
    ],
    'moody_info_bars' => [
      'variables' => [
        'title' => NULL,
        'link' => NULL,
      ],
      'template' => 'moody-info-bars',
    ],
    'field__moody_info_bars' => [
      'base hook' => 'field',
      'template' => 'field--moody-info-bars',
    ],
    'field__moody_subsite_menu' => [
      'base hook' => 'field',
      'template' => 'field--moody-subsite-menu',
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function moody_subsite_form_moody_subsite_edit_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  if ($form_id == 'moody_subsite_edit_form') {
    // Get roles for currently logged in user.
    $current_user = \Drupal::currentUser();
    $roles = $current_user->getRoles();
    // Disable directory_structure field if user does not have adminstrator role.
    if (!in_array('moody_administrator', $roles)) {
      $form['directory_structure']['#attributes']['class'][] = 'visually-hidden';
    }
    
    
  }
}

/**
 * Implements hook_alter for the node form.
 */
function moody_subsite_form_node_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  // Add a state to be invisible via Drupal form API to the $form['subsite_blog_summary'] if the subsite_page checkbox is not checked
  $invisible_state_for_blog_checked = [
    ':input[name="field_subsite_blog_page[value]"]' => ['checked' => FALSE],
  ];
  $form['field_subsite_blog_image']['#states']['invisible'] = $invisible_state_for_blog_checked;
  $form['field_subsite_blog_summary']['#states']['invisible'] = $invisible_state_for_blog_checked;
}
