<?php

/**
 * @file
 * Primary module hooks for moody_charts module.
 */

/**
 * Implements hook_theme().
 */
function moody_charts_theme($existing, $type, $theme, $path) {
  return [
    'moody_charts' => [
      'variables' => [
        'chart_id'    => NULL,
        'chart_type'  => NULL,
        'chart_data'  => NULL,
        'chart_title' => NULL,
        'options'     => [],
      ],
    ],
  ];
}
